name: KATA KATA
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2802136540412903
title: KATA CERITERA KATA
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.46222140919417143
  lightness: 0.8899648275692016
  saturation: 0.9907998871058226
  rhythmicContrast: 0.34990481147542596
purpose: []
